// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: sor.proto

package sor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensRequest) Reset() {
	*x = ListTokensRequest{}
	mi := &file_sor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensRequest) ProtoMessage() {}

func (x *ListTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensRequest.ProtoReflect.Descriptor instead.
func (*ListTokensRequest) Descriptor() ([]byte, []int) {
	return file_sor_proto_rawDescGZIP(), []int{0}
}

type TokenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mint          string                 `protobuf:"bytes,1,opt,name=mint,proto3" json:"mint,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Decimals      uint32                 `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenInfo) Reset() {
	*x = TokenInfo{}
	mi := &file_sor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInfo) ProtoMessage() {}

func (x *TokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInfo.ProtoReflect.Descriptor instead.
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return file_sor_proto_rawDescGZIP(), []int{1}
}

func (x *TokenInfo) GetMint() string {
	if x != nil {
		return x.Mint
	}
	return ""
}

func (x *TokenInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TokenInfo) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

type ListTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenA        []*TokenInfo           `protobuf:"bytes,1,rep,name=token_a,json=tokenA,proto3" json:"token_a,omitempty"` // All tokens appearing as token_a in pools
	TokenB        []*TokenInfo           `protobuf:"bytes,2,rep,name=token_b,json=tokenB,proto3" json:"token_b,omitempty"` // All tokens appearing as token_b in pools
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensResponse) Reset() {
	*x = ListTokensResponse{}
	mi := &file_sor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensResponse) ProtoMessage() {}

func (x *ListTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensResponse.ProtoReflect.Descriptor instead.
func (*ListTokensResponse) Descriptor() ([]byte, []int) {
	return file_sor_proto_rawDescGZIP(), []int{2}
}

func (x *ListTokensResponse) GetTokenA() []*TokenInfo {
	if x != nil {
		return x.TokenA
	}
	return nil
}

func (x *ListTokensResponse) GetTokenB() []*TokenInfo {
	if x != nil {
		return x.TokenB
	}
	return nil
}

type QuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputToken    string                 `protobuf:"bytes,1,opt,name=input_token,json=inputToken,proto3" json:"input_token,omitempty"`
	OutputToken   string                 `protobuf:"bytes,2,opt,name=output_token,json=outputToken,proto3" json:"output_token,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteRequest) Reset() {
	*x = QuoteRequest{}
	mi := &file_sor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRequest) ProtoMessage() {}

func (x *QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRequest.ProtoReflect.Descriptor instead.
func (*QuoteRequest) Descriptor() ([]byte, []int) {
	return file_sor_proto_rawDescGZIP(), []int{3}
}

func (x *QuoteRequest) GetInputToken() string {
	if x != nil {
		return x.InputToken
	}
	return ""
}

func (x *QuoteRequest) GetOutputToken() string {
	if x != nil {
		return x.OutputToken
	}
	return ""
}

func (x *QuoteRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type QuoteResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InputToken        string                 `protobuf:"bytes,1,opt,name=input_token,json=inputToken,proto3" json:"input_token,omitempty"`
	OutputToken       string                 `protobuf:"bytes,2,opt,name=output_token,json=outputToken,proto3" json:"output_token,omitempty"`
	InputAmount       string                 `protobuf:"bytes,3,opt,name=input_amount,json=inputAmount,proto3" json:"input_amount,omitempty"`
	OutputAmount      string                 `protobuf:"bytes,4,opt,name=output_amount,json=outputAmount,proto3" json:"output_amount,omitempty"`
	Path              []string               `protobuf:"bytes,5,rep,name=path,proto3" json:"path,omitempty"` // Pool IDs
	PriceImpact       float64                `protobuf:"fixed64,6,opt,name=price_impact,json=priceImpact,proto3" json:"price_impact,omitempty"`
	TokenPath         []string               `protobuf:"bytes,7,rep,name=token_path,json=tokenPath,proto3" json:"token_path,omitempty"` // e.g., ["SOL", "USDC", "USDT"]
	HumanInputAmount  string                 `protobuf:"bytes,8,opt,name=human_input_amount,json=humanInputAmount,proto3" json:"human_input_amount,omitempty"`
	HumanOutputAmount string                 `protobuf:"bytes,9,opt,name=human_output_amount,json=humanOutputAmount,proto3" json:"human_output_amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QuoteResponse) Reset() {
	*x = QuoteResponse{}
	mi := &file_sor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteResponse) ProtoMessage() {}

func (x *QuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteResponse.ProtoReflect.Descriptor instead.
func (*QuoteResponse) Descriptor() ([]byte, []int) {
	return file_sor_proto_rawDescGZIP(), []int{4}
}

func (x *QuoteResponse) GetInputToken() string {
	if x != nil {
		return x.InputToken
	}
	return ""
}

func (x *QuoteResponse) GetOutputToken() string {
	if x != nil {
		return x.OutputToken
	}
	return ""
}

func (x *QuoteResponse) GetInputAmount() string {
	if x != nil {
		return x.InputAmount
	}
	return ""
}

func (x *QuoteResponse) GetOutputAmount() string {
	if x != nil {
		return x.OutputAmount
	}
	return ""
}

func (x *QuoteResponse) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *QuoteResponse) GetPriceImpact() float64 {
	if x != nil {
		return x.PriceImpact
	}
	return 0
}

func (x *QuoteResponse) GetTokenPath() []string {
	if x != nil {
		return x.TokenPath
	}
	return nil
}

func (x *QuoteResponse) GetHumanInputAmount() string {
	if x != nil {
		return x.HumanInputAmount
	}
	return ""
}

func (x *QuoteResponse) GetHumanOutputAmount() string {
	if x != nil {
		return x.HumanOutputAmount
	}
	return ""
}

type SwapRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	InputToken                string                 `protobuf:"bytes,1,opt,name=input_token,json=inputToken,proto3" json:"input_token,omitempty"`
	OutputToken               string                 `protobuf:"bytes,2,opt,name=output_token,json=outputToken,proto3" json:"output_token,omitempty"`
	Amount                    string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	UserAddress               string                 `protobuf:"bytes,4,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
	SlippageBps               float64                `protobuf:"fixed64,5,opt,name=slippage_bps,json=slippageBps,proto3" json:"slippage_bps,omitempty"`
	RecentBlockhash           string                 `protobuf:"bytes,6,opt,name=recent_blockhash,json=recentBlockhash,proto3" json:"recent_blockhash,omitempty"`
	PrioritizationFeeLamports uint64                 `protobuf:"varint,7,opt,name=prioritization_fee_lamports,json=prioritizationFeeLamports,proto3" json:"prioritization_fee_lamports,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SwapRequest) Reset() {
	*x = SwapRequest{}
	mi := &file_sor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapRequest) ProtoMessage() {}

func (x *SwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapRequest.ProtoReflect.Descriptor instead.
func (*SwapRequest) Descriptor() ([]byte, []int) {
	return file_sor_proto_rawDescGZIP(), []int{5}
}

func (x *SwapRequest) GetInputToken() string {
	if x != nil {
		return x.InputToken
	}
	return ""
}

func (x *SwapRequest) GetOutputToken() string {
	if x != nil {
		return x.OutputToken
	}
	return ""
}

func (x *SwapRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *SwapRequest) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *SwapRequest) GetSlippageBps() float64 {
	if x != nil {
		return x.SlippageBps
	}
	return 0
}

func (x *SwapRequest) GetRecentBlockhash() string {
	if x != nil {
		return x.RecentBlockhash
	}
	return ""
}

func (x *SwapRequest) GetPrioritizationFeeLamports() uint64 {
	if x != nil {
		return x.PrioritizationFeeLamports
	}
	return 0
}

// A single candidate route with its token path and amounts.
type DetailedRoute struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TokenPath      []string               `protobuf:"bytes,1,rep,name=token_path,json=tokenPath,proto3" json:"token_path,omitempty"` // e.g., ["SOL", "USDC"]
	PoolIds        []string               `protobuf:"bytes,2,rep,name=pool_ids,json=poolIds,proto3" json:"pool_ids,omitempty"`       // Pool IDs used
	AmountIn       string                 `protobuf:"bytes,3,opt,name=amount_in,json=amountIn,proto3" json:"amount_in,omitempty"`
	AmountOut      string                 `protobuf:"bytes,4,opt,name=amount_out,json=amountOut,proto3" json:"amount_out,omitempty"`
	HumanAmountIn  string                 `protobuf:"bytes,5,opt,name=human_amount_in,json=humanAmountIn,proto3" json:"human_amount_in,omitempty"`
	HumanAmountOut string                 `protobuf:"bytes,6,opt,name=human_amount_out,json=humanAmountOut,proto3" json:"human_amount_out,omitempty"`
	PriceImpact    float64                `protobuf:"fixed64,7,opt,name=price_impact,json=priceImpact,proto3" json:"price_impact,omitempty"`
	DexLabels      []string               `protobuf:"bytes,8,rep,name=dex_labels,json=dexLabels,proto3" json:"dex_labels,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DetailedRoute) Reset() {
	*x = DetailedRoute{}
	mi := &file_sor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailedRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailedRoute) ProtoMessage() {}

func (x *DetailedRoute) ProtoReflect() protoreflect.Message {
	mi := &file_sor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailedRoute.ProtoReflect.Descriptor instead.
func (*DetailedRoute) Descriptor() ([]byte, []int) {
	return file_sor_proto_rawDescGZIP(), []int{6}
}

func (x *DetailedRoute) GetTokenPath() []string {
	if x != nil {
		return x.TokenPath
	}
	return nil
}

func (x *DetailedRoute) GetPoolIds() []string {
	if x != nil {
		return x.PoolIds
	}
	return nil
}

func (x *DetailedRoute) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *DetailedRoute) GetAmountOut() string {
	if x != nil {
		return x.AmountOut
	}
	return ""
}

func (x *DetailedRoute) GetHumanAmountIn() string {
	if x != nil {
		return x.HumanAmountIn
	}
	return ""
}

func (x *DetailedRoute) GetHumanAmountOut() string {
	if x != nil {
		return x.HumanAmountOut
	}
	return ""
}

func (x *DetailedRoute) GetPriceImpact() float64 {
	if x != nil {
		return x.PriceImpact
	}
	return 0
}

func (x *DetailedRoute) GetDexLabels() []string {
	if x != nil {
		return x.DexLabels
	}
	return nil
}

type SwapResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message           string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Route             []string               `protobuf:"bytes,4,rep,name=route,proto3" json:"route,omitempty"` // Best route token path (kept for backwards compat)
	OutputAmount      string                 `protobuf:"bytes,5,opt,name=output_amount,json=outputAmount,proto3" json:"output_amount,omitempty"`
	HumanOutputAmount string                 `protobuf:"bytes,6,opt,name=human_output_amount,json=humanOutputAmount,proto3" json:"human_output_amount,omitempty"`
	Routes            []*DetailedRoute       `protobuf:"bytes,7,rep,name=routes,proto3" json:"routes,omitempty"` // All routes, sorted best (highest output) first
	Transaction       []byte                 `protobuf:"bytes,8,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SwapResponse) Reset() {
	*x = SwapResponse{}
	mi := &file_sor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapResponse) ProtoMessage() {}

func (x *SwapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapResponse.ProtoReflect.Descriptor instead.
func (*SwapResponse) Descriptor() ([]byte, []int) {
	return file_sor_proto_rawDescGZIP(), []int{7}
}

func (x *SwapResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SwapResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SwapResponse) GetRoute() []string {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *SwapResponse) GetOutputAmount() string {
	if x != nil {
		return x.OutputAmount
	}
	return ""
}

func (x *SwapResponse) GetHumanOutputAmount() string {
	if x != nil {
		return x.HumanOutputAmount
	}
	return ""
}

func (x *SwapResponse) GetRoutes() []*DetailedRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *SwapResponse) GetTransaction() []byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

var File_sor_proto protoreflect.FileDescriptor

const file_sor_proto_rawDesc = "" +
	"\n" +
	"\tsor.proto\x12\x03sor\"\x13\n" +
	"\x11ListTokensRequest\"S\n" +
	"\tTokenInfo\x12\x12\n" +
	"\x04mint\x18\x01 \x01(\tR\x04mint\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bdecimals\x18\x03 \x01(\rR\bdecimals\"f\n" +
	"\x12ListTokensResponse\x12'\n" +
	"\atoken_a\x18\x01 \x03(\v2\x0e.sor.TokenInfoR\x06tokenA\x12'\n" +
	"\atoken_b\x18\x02 \x03(\v2\x0e.sor.TokenInfoR\x06tokenB\"j\n" +
	"\fQuoteRequest\x12\x1f\n" +
	"\vinput_token\x18\x01 \x01(\tR\n" +
	"inputToken\x12!\n" +
	"\foutput_token\x18\x02 \x01(\tR\voutputToken\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"\xcf\x02\n" +
	"\rQuoteResponse\x12\x1f\n" +
	"\vinput_token\x18\x01 \x01(\tR\n" +
	"inputToken\x12!\n" +
	"\foutput_token\x18\x02 \x01(\tR\voutputToken\x12!\n" +
	"\finput_amount\x18\x03 \x01(\tR\vinputAmount\x12#\n" +
	"\routput_amount\x18\x04 \x01(\tR\foutputAmount\x12\x12\n" +
	"\x04path\x18\x05 \x03(\tR\x04path\x12!\n" +
	"\fprice_impact\x18\x06 \x01(\x01R\vpriceImpact\x12\x1d\n" +
	"\n" +
	"token_path\x18\a \x03(\tR\ttokenPath\x12,\n" +
	"\x12human_input_amount\x18\b \x01(\tR\x10humanInputAmount\x12.\n" +
	"\x13human_output_amount\x18\t \x01(\tR\x11humanOutputAmount\"\x9a\x02\n" +
	"\vSwapRequest\x12\x1f\n" +
	"\vinput_token\x18\x01 \x01(\tR\n" +
	"inputToken\x12!\n" +
	"\foutput_token\x18\x02 \x01(\tR\voutputToken\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12!\n" +
	"\fuser_address\x18\x04 \x01(\tR\vuserAddress\x12!\n" +
	"\fslippage_bps\x18\x05 \x01(\x01R\vslippageBps\x12)\n" +
	"\x10recent_blockhash\x18\x06 \x01(\tR\x0frecentBlockhash\x12>\n" +
	"\x1bprioritization_fee_lamports\x18\a \x01(\x04R\x19prioritizationFeeLamports\"\x99\x02\n" +
	"\rDetailedRoute\x12\x1d\n" +
	"\n" +
	"token_path\x18\x01 \x03(\tR\ttokenPath\x12\x19\n" +
	"\bpool_ids\x18\x02 \x03(\tR\apoolIds\x12\x1b\n" +
	"\tamount_in\x18\x03 \x01(\tR\bamountIn\x12\x1d\n" +
	"\n" +
	"amount_out\x18\x04 \x01(\tR\tamountOut\x12&\n" +
	"\x0fhuman_amount_in\x18\x05 \x01(\tR\rhumanAmountIn\x12(\n" +
	"\x10human_amount_out\x18\x06 \x01(\tR\x0ehumanAmountOut\x12!\n" +
	"\fprice_impact\x18\a \x01(\x01R\vpriceImpact\x12\x1d\n" +
	"\n" +
	"dex_labels\x18\b \x03(\tR\tdexLabels\"\xf9\x01\n" +
	"\fSwapResponse\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05route\x18\x04 \x03(\tR\x05route\x12#\n" +
	"\routput_amount\x18\x05 \x01(\tR\foutputAmount\x12.\n" +
	"\x13human_output_amount\x18\x06 \x01(\tR\x11humanOutputAmount\x12*\n" +
	"\x06routes\x18\a \x03(\v2\x12.sor.DetailedRouteR\x06routes\x12 \n" +
	"\vtransaction\x18\b \x01(\fR\vtransaction2\xa8\x01\n" +
	"\n" +
	"SORService\x12.\n" +
	"\x05Quote\x12\x11.sor.QuoteRequest\x1a\x12.sor.QuoteResponse\x12+\n" +
	"\x04Swap\x12\x10.sor.SwapRequest\x1a\x11.sor.SwapResponse\x12=\n" +
	"\n" +
	"ListTokens\x12\x16.sor.ListTokensRequest\x1a\x17.sor.ListTokensResponseB/Z-github.com/dexAggregator/APIGateway/proto/sorb\x06proto3"

var (
	file_sor_proto_rawDescOnce sync.Once
	file_sor_proto_rawDescData []byte
)

func file_sor_proto_rawDescGZIP() []byte {
	file_sor_proto_rawDescOnce.Do(func() {
		file_sor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sor_proto_rawDesc), len(file_sor_proto_rawDesc)))
	})
	return file_sor_proto_rawDescData
}

var file_sor_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sor_proto_goTypes = []any{
	(*ListTokensRequest)(nil),  // 0: sor.ListTokensRequest
	(*TokenInfo)(nil),          // 1: sor.TokenInfo
	(*ListTokensResponse)(nil), // 2: sor.ListTokensResponse
	(*QuoteRequest)(nil),       // 3: sor.QuoteRequest
	(*QuoteResponse)(nil),      // 4: sor.QuoteResponse
	(*SwapRequest)(nil),        // 5: sor.SwapRequest
	(*DetailedRoute)(nil),      // 6: sor.DetailedRoute
	(*SwapResponse)(nil),       // 7: sor.SwapResponse
}
var file_sor_proto_depIdxs = []int32{
	1, // 0: sor.ListTokensResponse.token_a:type_name -> sor.TokenInfo
	1, // 1: sor.ListTokensResponse.token_b:type_name -> sor.TokenInfo
	6, // 2: sor.SwapResponse.routes:type_name -> sor.DetailedRoute
	3, // 3: sor.SORService.Quote:input_type -> sor.QuoteRequest
	5, // 4: sor.SORService.Swap:input_type -> sor.SwapRequest
	0, // 5: sor.SORService.ListTokens:input_type -> sor.ListTokensRequest
	4, // 6: sor.SORService.Quote:output_type -> sor.QuoteResponse
	7, // 7: sor.SORService.Swap:output_type -> sor.SwapResponse
	2, // 8: sor.SORService.ListTokens:output_type -> sor.ListTokensResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sor_proto_init() }
func file_sor_proto_init() {
	if File_sor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sor_proto_rawDesc), len(file_sor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sor_proto_goTypes,
		DependencyIndexes: file_sor_proto_depIdxs,
		MessageInfos:      file_sor_proto_msgTypes,
	}.Build()
	File_sor_proto = out.File
	file_sor_proto_goTypes = nil
	file_sor_proto_depIdxs = nil
}
