// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.6.1
// source: proto/sor.proto

package sor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SORService_Quote_FullMethodName = "/sor.SORService/Quote"
	SORService_Swap_FullMethodName  = "/sor.SORService/Swap"
)

// SORServiceClient is the client API for SORService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SORServiceClient interface {
	Quote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error)
	Swap(ctx context.Context, in *SwapRequest, opts ...grpc.CallOption) (*SwapResponse, error)
}

type sORServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSORServiceClient(cc grpc.ClientConnInterface) SORServiceClient {
	return &sORServiceClient{cc}
}

func (c *sORServiceClient) Quote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuoteResponse)
	err := c.cc.Invoke(ctx, SORService_Quote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sORServiceClient) Swap(ctx context.Context, in *SwapRequest, opts ...grpc.CallOption) (*SwapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwapResponse)
	err := c.cc.Invoke(ctx, SORService_Swap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SORServiceServer is the server API for SORService service.
// All implementations must embed UnimplementedSORServiceServer
// for forward compatibility.
type SORServiceServer interface {
	Quote(context.Context, *QuoteRequest) (*QuoteResponse, error)
	Swap(context.Context, *SwapRequest) (*SwapResponse, error)
	mustEmbedUnimplementedSORServiceServer()
}

// UnimplementedSORServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSORServiceServer struct{}

func (UnimplementedSORServiceServer) Quote(context.Context, *QuoteRequest) (*QuoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Quote not implemented")
}
func (UnimplementedSORServiceServer) Swap(context.Context, *SwapRequest) (*SwapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Swap not implemented")
}
func (UnimplementedSORServiceServer) mustEmbedUnimplementedSORServiceServer() {}
func (UnimplementedSORServiceServer) testEmbeddedByValue()                    {}

// UnsafeSORServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SORServiceServer will
// result in compilation errors.
type UnsafeSORServiceServer interface {
	mustEmbedUnimplementedSORServiceServer()
}

func RegisterSORServiceServer(s grpc.ServiceRegistrar, srv SORServiceServer) {
	// If the following call panics, it indicates UnimplementedSORServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SORService_ServiceDesc, srv)
}

func _SORService_Quote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SORServiceServer).Quote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SORService_Quote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SORServiceServer).Quote(ctx, req.(*QuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SORService_Swap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SORServiceServer).Swap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SORService_Swap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SORServiceServer).Swap(ctx, req.(*SwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SORService_ServiceDesc is the grpc.ServiceDesc for SORService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SORService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sor.SORService",
	HandlerType: (*SORServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Quote",
			Handler:    _SORService_Quote_Handler,
		},
		{
			MethodName: "Swap",
			Handler:    _SORService_Swap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sor.proto",
}
