// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.6.1
// source: proto/oracle.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PriceOracle_GetPoolReserves_FullMethodName   = "/oracle.PriceOracle/GetPoolReserves"
	PriceOracle_GetMonitoredPools_FullMethodName = "/oracle.PriceOracle/GetMonitoredPools"
)

// PriceOracleClient is the client API for PriceOracle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PriceOracleClient interface {
	GetPoolReserves(ctx context.Context, in *PoolRequest, opts ...grpc.CallOption) (*PoolUpdate, error)
	GetMonitoredPools(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PoolList, error)
}

type priceOracleClient struct {
	cc grpc.ClientConnInterface
}

func NewPriceOracleClient(cc grpc.ClientConnInterface) PriceOracleClient {
	return &priceOracleClient{cc}
}

func (c *priceOracleClient) GetPoolReserves(ctx context.Context, in *PoolRequest, opts ...grpc.CallOption) (*PoolUpdate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PoolUpdate)
	err := c.cc.Invoke(ctx, PriceOracle_GetPoolReserves_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceOracleClient) GetMonitoredPools(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PoolList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PoolList)
	err := c.cc.Invoke(ctx, PriceOracle_GetMonitoredPools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PriceOracleServer is the server API for PriceOracle service.
// All implementations must embed UnimplementedPriceOracleServer
// for forward compatibility.
type PriceOracleServer interface {
	GetPoolReserves(context.Context, *PoolRequest) (*PoolUpdate, error)
	GetMonitoredPools(context.Context, *Empty) (*PoolList, error)
	mustEmbedUnimplementedPriceOracleServer()
}

// UnimplementedPriceOracleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPriceOracleServer struct{}

func (UnimplementedPriceOracleServer) GetPoolReserves(context.Context, *PoolRequest) (*PoolUpdate, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPoolReserves not implemented")
}
func (UnimplementedPriceOracleServer) GetMonitoredPools(context.Context, *Empty) (*PoolList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMonitoredPools not implemented")
}
func (UnimplementedPriceOracleServer) mustEmbedUnimplementedPriceOracleServer() {}
func (UnimplementedPriceOracleServer) testEmbeddedByValue()                     {}

// UnsafePriceOracleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PriceOracleServer will
// result in compilation errors.
type UnsafePriceOracleServer interface {
	mustEmbedUnimplementedPriceOracleServer()
}

func RegisterPriceOracleServer(s grpc.ServiceRegistrar, srv PriceOracleServer) {
	// If the following call panics, it indicates UnimplementedPriceOracleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PriceOracle_ServiceDesc, srv)
}

func _PriceOracle_GetPoolReserves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceOracleServer).GetPoolReserves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PriceOracle_GetPoolReserves_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceOracleServer).GetPoolReserves(ctx, req.(*PoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceOracle_GetMonitoredPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceOracleServer).GetMonitoredPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PriceOracle_GetMonitoredPools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceOracleServer).GetMonitoredPools(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PriceOracle_ServiceDesc is the grpc.ServiceDesc for PriceOracle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PriceOracle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oracle.PriceOracle",
	HandlerType: (*PriceOracleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPoolReserves",
			Handler:    _PriceOracle_GetPoolReserves_Handler,
		},
		{
			MethodName: "GetMonitoredPools",
			Handler:    _PriceOracle_GetMonitoredPools_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/oracle.proto",
}
