// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: oracle.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_oracle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{0}
}

type PoolList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolIds       []string               `protobuf:"bytes,1,rep,name=pool_ids,json=poolIds,proto3" json:"pool_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolList) Reset() {
	*x = PoolList{}
	mi := &file_oracle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolList) ProtoMessage() {}

func (x *PoolList) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolList.ProtoReflect.Descriptor instead.
func (*PoolList) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{1}
}

func (x *PoolList) GetPoolIds() []string {
	if x != nil {
		return x.PoolIds
	}
	return nil
}

type PoolUpdateList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       []*PoolUpdate          `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolUpdateList) Reset() {
	*x = PoolUpdateList{}
	mi := &file_oracle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolUpdateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolUpdateList) ProtoMessage() {}

func (x *PoolUpdateList) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolUpdateList.ProtoReflect.Descriptor instead.
func (*PoolUpdateList) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{2}
}

func (x *PoolUpdateList) GetUpdates() []*PoolUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

type PoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolRequest) Reset() {
	*x = PoolRequest{}
	mi := &file_oracle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolRequest) ProtoMessage() {}

func (x *PoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolRequest.ProtoReflect.Descriptor instead.
func (*PoolRequest) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{3}
}

func (x *PoolRequest) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DexTypes      []string               `protobuf:"bytes,1,rep,name=dex_types,json=dexTypes,proto3" json:"dex_types,omitempty"` // e.g., ["raydium", "orca"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_oracle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{4}
}

func (x *StreamRequest) GetDexTypes() []string {
	if x != nil {
		return x.DexTypes
	}
	return nil
}

type PoolUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	TokenA        string                 `protobuf:"bytes,2,opt,name=token_a,json=tokenA,proto3" json:"token_a,omitempty"`
	TokenB        string                 `protobuf:"bytes,3,opt,name=token_b,json=tokenB,proto3" json:"token_b,omitempty"`
	ReserveA      uint64                 `protobuf:"varint,4,opt,name=reserve_a,json=reserveA,proto3" json:"reserve_a,omitempty"`
	ReserveB      uint64                 `protobuf:"varint,5,opt,name=reserve_b,json=reserveB,proto3" json:"reserve_b,omitempty"`
	AmmType       uint32                 `protobuf:"varint,6,opt,name=amm_type,json=ammType,proto3" json:"amm_type,omitempty"`      // 0 for AMM, 1 for CLMM
	ExtraData     []byte                 `protobuf:"bytes,7,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"` // For CLMM tick bitmaps
	SymbolA       string                 `protobuf:"bytes,8,opt,name=symbol_a,json=symbolA,proto3" json:"symbol_a,omitempty"`
	SymbolB       string                 `protobuf:"bytes,9,opt,name=symbol_b,json=symbolB,proto3" json:"symbol_b,omitempty"`
	DecimalsA     uint32                 `protobuf:"varint,10,opt,name=decimals_a,json=decimalsA,proto3" json:"decimals_a,omitempty"`
	DecimalsB     uint32                 `protobuf:"varint,11,opt,name=decimals_b,json=decimalsB,proto3" json:"decimals_b,omitempty"`
	DexLabel      string                 `protobuf:"bytes,12,opt,name=dex_label,json=dexLabel,proto3" json:"dex_label,omitempty"`
	Accounts      map[string]string      `protobuf:"bytes,13,rep,name=accounts,proto3" json:"accounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolUpdate) Reset() {
	*x = PoolUpdate{}
	mi := &file_oracle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolUpdate) ProtoMessage() {}

func (x *PoolUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolUpdate.ProtoReflect.Descriptor instead.
func (*PoolUpdate) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{5}
}

func (x *PoolUpdate) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *PoolUpdate) GetTokenA() string {
	if x != nil {
		return x.TokenA
	}
	return ""
}

func (x *PoolUpdate) GetTokenB() string {
	if x != nil {
		return x.TokenB
	}
	return ""
}

func (x *PoolUpdate) GetReserveA() uint64 {
	if x != nil {
		return x.ReserveA
	}
	return 0
}

func (x *PoolUpdate) GetReserveB() uint64 {
	if x != nil {
		return x.ReserveB
	}
	return 0
}

func (x *PoolUpdate) GetAmmType() uint32 {
	if x != nil {
		return x.AmmType
	}
	return 0
}

func (x *PoolUpdate) GetExtraData() []byte {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

func (x *PoolUpdate) GetSymbolA() string {
	if x != nil {
		return x.SymbolA
	}
	return ""
}

func (x *PoolUpdate) GetSymbolB() string {
	if x != nil {
		return x.SymbolB
	}
	return ""
}

func (x *PoolUpdate) GetDecimalsA() uint32 {
	if x != nil {
		return x.DecimalsA
	}
	return 0
}

func (x *PoolUpdate) GetDecimalsB() uint32 {
	if x != nil {
		return x.DecimalsB
	}
	return 0
}

func (x *PoolUpdate) GetDexLabel() string {
	if x != nil {
		return x.DexLabel
	}
	return ""
}

func (x *PoolUpdate) GetAccounts() map[string]string {
	if x != nil {
		return x.Accounts
	}
	return nil
}

var File_oracle_proto protoreflect.FileDescriptor

const file_oracle_proto_rawDesc = "" +
	"\n" +
	"\foracle.proto\x12\x06oracle\"\a\n" +
	"\x05Empty\"%\n" +
	"\bPoolList\x12\x19\n" +
	"\bpool_ids\x18\x01 \x03(\tR\apoolIds\">\n" +
	"\x0ePoolUpdateList\x12,\n" +
	"\aupdates\x18\x01 \x03(\v2\x12.oracle.PoolUpdateR\aupdates\"&\n" +
	"\vPoolRequest\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\",\n" +
	"\rStreamRequest\x12\x1b\n" +
	"\tdex_types\x18\x01 \x03(\tR\bdexTypes\"\xd7\x03\n" +
	"\n" +
	"PoolUpdate\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\x12\x17\n" +
	"\atoken_a\x18\x02 \x01(\tR\x06tokenA\x12\x17\n" +
	"\atoken_b\x18\x03 \x01(\tR\x06tokenB\x12\x1b\n" +
	"\treserve_a\x18\x04 \x01(\x04R\breserveA\x12\x1b\n" +
	"\treserve_b\x18\x05 \x01(\x04R\breserveB\x12\x19\n" +
	"\bamm_type\x18\x06 \x01(\rR\aammType\x12\x1d\n" +
	"\n" +
	"extra_data\x18\a \x01(\fR\textraData\x12\x19\n" +
	"\bsymbol_a\x18\b \x01(\tR\asymbolA\x12\x19\n" +
	"\bsymbol_b\x18\t \x01(\tR\asymbolB\x12\x1d\n" +
	"\n" +
	"decimals_a\x18\n" +
	" \x01(\rR\tdecimalsA\x12\x1d\n" +
	"\n" +
	"decimals_b\x18\v \x01(\rR\tdecimalsB\x12\x1b\n" +
	"\tdex_label\x18\f \x01(\tR\bdexLabel\x12<\n" +
	"\baccounts\x18\r \x03(\v2 .oracle.PoolUpdate.AccountsEntryR\baccounts\x1a;\n" +
	"\rAccountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xbb\x01\n" +
	"\vPriceOracle\x12:\n" +
	"\x0fGetPoolReserves\x12\x13.oracle.PoolRequest\x1a\x12.oracle.PoolUpdate\x124\n" +
	"\x11GetMonitoredPools\x12\r.oracle.Empty\x1a\x10.oracle.PoolList\x12:\n" +
	"\x11GetAllPoolUpdates\x12\r.oracle.Empty\x1a\x16.oracle.PoolUpdateListB\x1aZ\x18priceOracleService/protob\x06proto3"

var (
	file_oracle_proto_rawDescOnce sync.Once
	file_oracle_proto_rawDescData []byte
)

func file_oracle_proto_rawDescGZIP() []byte {
	file_oracle_proto_rawDescOnce.Do(func() {
		file_oracle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oracle_proto_rawDesc), len(file_oracle_proto_rawDesc)))
	})
	return file_oracle_proto_rawDescData
}

var file_oracle_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_oracle_proto_goTypes = []any{
	(*Empty)(nil),          // 0: oracle.Empty
	(*PoolList)(nil),       // 1: oracle.PoolList
	(*PoolUpdateList)(nil), // 2: oracle.PoolUpdateList
	(*PoolRequest)(nil),    // 3: oracle.PoolRequest
	(*StreamRequest)(nil),  // 4: oracle.StreamRequest
	(*PoolUpdate)(nil),     // 5: oracle.PoolUpdate
	nil,                    // 6: oracle.PoolUpdate.AccountsEntry
}
var file_oracle_proto_depIdxs = []int32{
	5, // 0: oracle.PoolUpdateList.updates:type_name -> oracle.PoolUpdate
	6, // 1: oracle.PoolUpdate.accounts:type_name -> oracle.PoolUpdate.AccountsEntry
	3, // 2: oracle.PriceOracle.GetPoolReserves:input_type -> oracle.PoolRequest
	0, // 3: oracle.PriceOracle.GetMonitoredPools:input_type -> oracle.Empty
	0, // 4: oracle.PriceOracle.GetAllPoolUpdates:input_type -> oracle.Empty
	5, // 5: oracle.PriceOracle.GetPoolReserves:output_type -> oracle.PoolUpdate
	1, // 6: oracle.PriceOracle.GetMonitoredPools:output_type -> oracle.PoolList
	2, // 7: oracle.PriceOracle.GetAllPoolUpdates:output_type -> oracle.PoolUpdateList
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_oracle_proto_init() }
func file_oracle_proto_init() {
	if File_oracle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oracle_proto_rawDesc), len(file_oracle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oracle_proto_goTypes,
		DependencyIndexes: file_oracle_proto_depIdxs,
		MessageInfos:      file_oracle_proto_msgTypes,
	}.Build()
	File_oracle_proto = out.File
	file_oracle_proto_goTypes = nil
	file_oracle_proto_depIdxs = nil
}
