// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/quote": {
            "post": {
                "description": "Find the best route and output amount for a swap",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "swap"
                ],
                "summary": "Get a token swap quote",
                "parameters": [
                    {
                        "description": "Quote Request",
                        "name": "quote",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.QuoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/sor.QuoteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/swap": {
            "post": {
                "description": "Initiate a swap transaction via the SOR",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "swap"
                ],
                "summary": "Execute a token swap",
                "parameters": [
                    {
                        "description": "Swap Request",
                        "name": "swap",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.SwapRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/sor.SwapResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.QuoteRequest": {
            "type": "object",
            "required": [
                "amount",
                "inputToken",
                "outputToken"
            ],
            "properties": {
                "amount": {
                    "type": "string"
                },
                "inputToken": {
                    "type": "string"
                },
                "outputToken": {
                    "type": "string"
                }
            }
        },
        "handlers.SwapRequest": {
            "type": "object",
            "required": [
                "amount",
                "inputToken",
                "outputToken",
                "userAddress"
            ],
            "properties": {
                "amount": {
                    "type": "string"
                },
                "inputToken": {
                    "type": "string"
                },
                "outputToken": {
                    "type": "string"
                },
                "slippageBps": {
                    "description": "0 to 10%",
                    "type": "number",
                    "maximum": 1000,
                    "minimum": 0
                },
                "userAddress": {
                    "type": "string"
                }
            }
        },
        "sor.QuoteResponse": {
            "type": "object",
            "properties": {
                "input_amount": {
                    "type": "string"
                },
                "input_token": {
                    "type": "string"
                },
                "output_amount": {
                    "type": "string"
                },
                "output_token": {
                    "type": "string"
                },
                "path": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "price_impact": {
                    "type": "number"
                }
            }
        },
        "sor.SwapResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tx_hash": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "DEX Aggregator API Gateway",
	Description:      "API Gateway for the Solana DEX Aggregator.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
